### ISSUE TITLE
tutorials

### ISSUE THREAD

**Issue by jjhesk** [StanKocken/SVG2Drawable#1]
Can I have more tutorials how to include this library on grade android studio?

**Comment by StanKocken** [comment]
I don't use this library directly with Gradle / Android Studio. The main goal of this library is to generate the code to display your image, that you can store into your project to use directly.

I just uploaded a diagram to explain this more clearly:
![diagram](https://raw.githubusercontent.com/StanKocken/SVG2Drawable/master/svg_to_drawable.png)

Is that useful for you?

**Comment by jjhesk** [comment]
I see, that is a standalone library app to converter the svg into drawable but its not making the drawable on runtime.

**Comment by StanKocken** [comment]
Yes exactly, I just added this sentence into my ReadMe.

**Comment by jjhesk** [comment]
is that possible to have the svg downloaded from htto processor and make conversion after as an android library?

**Comment by StanKocken** [comment]
At the runtime, it won't be possible to reduce the time to parse.
Maybe there is something to do for the Hardware acceleration part (by not using a "Picture" like svg-android did). I will think about that.

**Comment by pfaffenrodt** [comment]
What SVG version is supported?

**Comment by StanKocken** [comment]
I cannot guarantee that this library is 100% compatible with any SVG version.
I do my best to fix it anytime I have an issue on my own cases.
