### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pfaffenrodt** [StanKocken/SVG2Drawable#3]
Exported Illustrator SVGs throws Nullpointer Exception.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
```

SVGHandler throws Nullpointer at line 273 

``` java
width = (int) Math.ceil(getFloatAttr("width", atts));
```

SVG width and hight is set by the viewBox attribute.

**Comment by StanKocken** [comment]
Yeah you're right, I remember this issue with the original SVG library I used.
I agree, in this case I should take the width and height from the viewBox.
I will do the modification when I got a minute later today.

**Comment by pfaffenrodt** [comment]
getFloatAttr defaultValue is null.

``` java
width = (int) Math.ceil(getFloatAttr("width", atts,0f));
height = (int) Math.ceil(getFloatAttr("height", atts,0f));
```

I set the defaultValue to 0f.

And also take width and height from viewBox

**Comment by StanKocken** [comment]
Yes, it could be awesome if you can do a pull request with that. If you can't don't worry, I will but just not now.
